import nodemailer from 'nodemailer';


export default async function handler(req, res) {
  console.log('--- API HANDLER START ---');

  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method Not Allowed' });
  }

  const { fullName, email, message, service } = req.body;

  if (!fullName || !email || !message) {
    return res.status(400).json({ success: false, message: 'Required fields missing.' });
  }

  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
    return res.status(500).json({ success: false, message: 'Server configuration error.' });
  }

  const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    secure: true,
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  try {
    // 1. Internal Studio Alert (Simplified for fast reading)
    await transporter.sendMail({
      from: `"Studio Dashboard" <${process.env.EMAIL_USER}>`,
      to: process.env.EMAIL_USER,
      subject: `[STUDIO INTAKE] ${fullName}`,
      html: `
        <div style="font-family: 'Helvetica', sans-serif; padding: 40px; background: #faf9fb; color: #1b1c1e;">
          <p style="text-transform: uppercase; letter-spacing: 0.3em; font-size: 10px; color: #b81400; font-weight: bold; margin-bottom: 20px;">New Intake Received</p>
          <h1 style="font-size: 32px; font-weight: 900; margin: 0 0 40px 0; border-bottom: 1px solid rgba(0,0,0,0.05); padding-bottom: 20px;">${fullName}</h1>
          <div style="margin-bottom: 30px;">
            <p style="font-size: 12px; opacity: 0.5; text-transform: uppercase; margin-bottom: 5px;">Client Information</p>
            <p style="margin: 0; font-size: 16px;"><strong>Email:</strong> ${email}</p>
            <p style="margin: 5px 0 0 0; font-size: 16px;"><strong>Interests:</strong> ${service}</p>
          </div>
          <div>
            <p style="font-size: 12px; opacity: 0.5; text-transform: uppercase; margin-bottom: 5px;">The Brief</p>
            <p style="margin: 0; font-weight: normal; font-size: 18px; line-height: 1.6; color: #333 italic;">"${message}"</p>
          </div>
          <p style="margin-top: 60px; font-size: 10px; opacity: 0.3; text-transform: uppercase; letter-spacing: 0.1em;">Transmission generated by Digital Symphony Engine v2.0</p>
        </div>
      `,
      replyTo: email
    });

    // 2. Client Acknowledgement (The Brand Experience)
    await transporter.sendMail({
      from: `"Deepansh Kushwaha [Studio]" <${process.env.EMAIL_USER}>`,
      to: email,
      subject: `Signal Received: Your inquiry with the Studio`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <link href="https://fonts.googleapis.com/css2?family=Epilogue:wght@900&family=Manrope:wght@300;400;600&display=swap" rel="stylesheet">
          <style>
            body { margin: 0; padding: 0; background-color: #faf9fb; font-family: 'Manrope', 'Helvetica', sans-serif; color: #1b1c1e; }
            .container { max-width: 600px; margin: 0 auto; padding: 60px 20px; }
            .label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.4em; color: #b81400; font-weight: bold; margin-bottom: 30px; }
            .headline { font-family: 'Epilogue', sans-serif; font-size: 48px; line-height: 0.95; font-weight: 900; margin-bottom: 40px; text-transform: uppercase; }
            .content { font-size: 18px; line-height: 1.8; font-weight: 300; opacity: 0.8; margin-bottom: 60px; }
            .brief-box { background: #ffffff; border: 1px solid rgba(0,0,0,0.03); padding: 40px; margin-bottom: 60px; border-radius: 4px; box-shadow: 0 10px 40px rgba(0,0,0,0.02); }
            .brief-label { font-size: 9px; text-transform: uppercase; letter-spacing: 0.2em; opacity: 0.4; margin-bottom: 15px; display: block; }
            .brief-text { font-size: 15px; font-style: italic; opacity: 0.7; border-left: 2px solid #b81400; padding-left: 20px; }
            .footer { border-top: 1px solid rgba(0,0,0,0.05); padding-top: 40px; font-size: 11px; opacity: 0.4; text-transform: uppercase; letter-spacing: 0.1em; }
            .accent { color: #b81400; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="label">Studio Transmission</div>
            <div class="headline">Growth<br/><span class="accent">CONFIRMED.</span></div>
            <div class="content">
              Hello ${fullName},<br/><br/>
              We have successfully received your inquiry regarding <strong>${service}</strong>. Our team is analyzing your brief, and we will contact you shortly to discuss how we can bring your vision to life.
            </div>
            <div class="brief-box">
              <span class="brief-label">THE RECORDED BRIEF</span>
              <div class="brief-text">"${message}"</div>
            </div>
            <div class="content">
              Expect a formal response within 24 standard business hours to discuss the engineering precision of your next digital symphony.
            </div>
            <div class="footer">
              Deepansh Kushwaha Studio<br/>
              Digital Excellence | Engineering Precision
            </div>
          </div>
        </body>
        </html>
      `,
      replyTo: process.env.EMAIL_USER
    });

    return res.status(200).json({ success: true, message: 'Mission Transmitted Successfully' });

  } catch (error) {
    console.error('CRITICAL MAILER FAULT:', error);
    return res.status(500).json({ success: false, message: 'Electronic transmission failed.' });
  }
}
